### ISSUE TITLE
Stable yt_astro_analysis v1.0.0 does not work with yt dev master branch

### ISSUE THREAD

**Issue by chummels** [yt-project/yt_astro_analysis#64] opened 2020-08-28 19:46 UTC
Due to some recent changes in the yt repository preparing for the yt-4.0 release, there were backwards-incompatible changes in the location of the `load` function, moving it from `convenience.py` to `loaders.py`.  These changes were imported into the `master` branch of this repository, but because of the backwards incompatibility, any codes using a stable version of this code with the development version of yt will be unable to run.  

Perhaps this is by design and yt_astro_analysis stable is only meant to work with yt stable and yt_astro_analysis development branch will only work with yt development branch?  I also noted that the most recent version found on PyPI and conda-forge servers appears to be v1.0.0, whereas in the code itself, there is reference to a 1.1.0, although this version appears prior to the fixes involving the `load` command.  

I am just confirming that this is the desired behavior.  If so, I can just ensure that trident dev requires a dev version of yt_astro_analysis to run properly.  Please advise.

**Comment by brittonsmith** [comment] 2020-09-04 14:00
This is the expected behavior. The latest stable yt_astro_analysis release is 1.0.0. The master branch is marked as 1.1.0.dev1, i.e., a pre-release of 1.1.0. There won't be another stable release of yt_astro_analysis until yt-4.0 is released.

**Comment by chummels** [comment] 2020-09-04 19:26
Thank you for the explanation.

**Comment by brittonsmith** [comment] 2021-03-11 12:20
I'm going to close this because it seems the discussion has concluded and I don't think there is anything that can be done here. The yt_astro_analysis package beyond version 1.0 is tied to yt-4.0, but we cannot release until yt-4.0 is released. That said, there's no reason we can't release as soon as the new yt is out.

**Closed by brittonsmith** 2021-03-11 12:20 UTC
