### ISSUE TITLE
Request for stable release to fix breakages in the stable version of the code

### ISSUE THREAD

**Issue by chummels** [yt-project/yt_astro_analysis#86] opened 2021-10-12 23:48 UTC
Ever since [yt PR # 2831](https://github.com/yt-project/yt/pull/2831) was merged into the yt-4 branch it has caused errors in any external packages that imported the `yt.load` function from yt (including `yt_astro_analysis`).  While `yt_astro_analysis` was prompt in patching this in its development branch, it doesn't yet have that patch in a stable version of the code, so anyone using `yt_astro_analysis` that was installed from pip or conda will encounter failures when using the `light_cone` and `cosmology_splice` modules.
 
I bring this up because `trident` cannot currently release a working stable version because it uses `yt_astro_analysis` as a dependency, and thus needs a stable working release on pip of `yt_astro_analysis`.  As far as I can tell the development version of `yt_astro_analysis` is all up to speed with `yt-4.0`, which means it's just a matter of making a point release of `yt_astro_analysis`.  I know this is not a trivial endeavor, but I would request there to be a new stable release of `yt_astro_analysis` at some point soon to keep abreast with the changes since yt4 was released, as the last release of `yt_astro_analysis` was in 2018.  I am happy to help with this where I can, as I'm hoping to also do a stable release of `trident` as soon as `yt_astro_analysis` is released.

**Comment by brittonsmith** [comment] 2021-11-01 10:02
I'm perfectly happy for someone to migrate this to github actions. I'm guessing the issue is related to the compiler being used in the docker image. The only thing I would do to try and figure this out is run with ssh enabled to allow me to log in and tinker. I'm fine with this falling back to me if no one else wants to take it on, but my time is 100% spoken for until the semester ends in another month.

**Comment by chummels** [comment] 2021-11-01 19:04
Is it possible to put out a new release of yt_astro_analysis prior to this bug being fixed?  I'm pretty bummed that the current stable release of Trident is broken, and I cannot release a new version until there is a new release of yt_astro_analysis due to the change in the location of the `yt.load()` function.

**Comment by matthewturk** [comment] 2021-11-01 20:40
I think that until someone is able to step up and fix the issues identified above (and @brittonsmith has already indicated he cannot right now) this is likely not to be resolved in the nearest of futures.

**Comment by chummels** [comment] 2021-11-01 22:04
This is unfortunate.

**Comment by neutrinoceros** [comment] 2021-11-02 07:34
I now it's not ideal, but as a bandaid, couldn't you simply pin yt<4.0 in trident release it ?

**Comment by brittonsmith** [comment] 2021-11-03 11:54
CI is now fixed and relevant PRs are merged. The release process has my blessing to move forward. I'm not sure if PR #87 is ready to go, but I don't have the expertise to evaluate it. We've only ever released yt-astro once, so I don't really have a sense of what steps we'll need to take to do it. If it requires additional steps from me, like release notes, then I will get to them when I can and not before.

**Comment by chummels** [comment] 2021-11-05 04:49
Thank you for the update and for the success in fixing the CI with rockstar. 

In terms of managing a release of yt_astro_analysis, is it nominally just following these procedures: https://yt-project.org/docs/dev/developing/releasing.html ?

Would this be yt_astro_analysis 2.0?  I could try to put together release notes, but I haven't really followed the PRs merged in the last few years, but I could probably try to summarize them based on their descriptions.

**Comment by neutrinoceros** [comment] 2021-11-05 07:05
The release procedure for yt is out of date. Also, GitHub release now now support automatically generated change logs, so it's much less of a pain to write :)

**Closed** 2021-12-15 14:25 UTC
